#!/bin/sh

checkSystemD() {
  if [[ "`cat /proc/1/comm`" = "systemd" ]]; then
    return True;
  fi
}

checkDistribution() {
  return `cat /etc/*release*|grep "^ID="|sed 's/"//g'|awk -F'[="]' '{print $NF}'`
}

deleteService() {
  if [[ checkSystemD ]]; then
    rm -f /lib/systemd/system/rundeckd.service
  else
    rm -f /etc/init.d/rundeckd
  fi
}

disableService() {
  if [[ checkSystemD ]]; then
    systemctl disable rundeckd
  else
    if [[ checkDistribution = "debian"  ]]; then
      update-rc.d rundeckd disable && update-rc.d -f rundeckd remove
    elif [[ checkDistribution = "centos" ]] || [[ -e /etc/centos-release ]] || [[ -e /etc/redhat-release ]]; then
      chkconfig rundeckd off && chkconfig --del rundeckd
    else
      echo "Can't determine distribution, please disable service manually."
    fi
  fi
}

case "$1" in
  failed-upgrade|abort-install|abort-upgrade|disappear|upgrade|1|2)
    ;;
  remove)
    ;;
  purge|0)
    disableService
    deleteService

    if getent passwd ${packagingAppUser} > /dev/null 2>&1; then
        userdel -rf ${packagingAppUser} > /dev/null 2>&1
    fi
    if getent group ${packagingAppGroup} > /dev/null 2>&1; then
        groupdel ${packagingAppGroup}
    fi

#    rm -rf ${packagingAppPrefix}
#    rm -rf ${packagingAppConfDir}
#    rm -rf ${packagingAppProjectPrefix}
#    rm -rf ${packagingAppLogDir}
#    rm -rf ${packagingAppTempDir}
    ;;
  *)
    echo "postrm called with unknown argument: $1" >&2
    exit 1
    ;;
esac

exit 0
