#!/bin/sh

checkSystemD() {
  if [[ "`cat /proc/1/comm`" = "systemd" ]]; then
    return True;
  fi
}

checkDistribution() {
  return `cat /etc/*release*|grep "^ID="|sed 's/"//g'|awk -F'[="]' '{print $NF}'`
}

prepareSshKey() {
  if [ ! -e ~${packagingAppUser}/.ssh/id_rsa ]; then
	  su -c "ssh-keygen -q -t rsa -C '' -N '' -f ~${packagingAppUser}/.ssh/id_rsa" ${packagingAppUser}
  fi
}

installService() {
  if [[ checkSystemD ]]; then
    ln -s ${packagingAppConfDir}/rundeckd.service /lib/systemd/system/rundeckd.service
  else
    ln -s ${packagingAppConfDir}/rundeckd /etc/init.d/rundeckd
  fi
}

enableService() {
  if [[ checkSystemD ]]; then
    systemctl enable rundeckd
  else
    if [[ checkDistribution = "debian"  ]]; then
      update-rc.d rundeckd enable
    elif [[ checkDistribution = "centos" ]] || [[ -e /etc/centos-release ]] || [[ -e /etc/redhat-release ]]; then
      chkconfig --add rundeckd && chkconfig rundeckd on
    else
      echo "Can't determine distribution, please enable service manually."
    fi
  fi
}
case "$1" in
  configure|1|2)
    prepareSshKey
    installService
    enableService
    ;;
  abort-upgrade|abort-remove|abort-deconfigure|0)
    ;;
  *)
    echo "postinst called with unknown argument \'$1\'" >&2
    exit 1
    ;;
esac

exit 0
