#!/bin/bash 
#
# rundeckd    Startup script for the rundeck
#
# chkconfig: 2345 90 10
# description: rundeckd, providing rundeckd
# pidfile: /var/run/rundeckd.pid

### BEGIN INIT INFO
# Provides:    rundeckd
# Required-Start:  $local_fs $network
# Required-Stop:  $local_fs $network
# Default-Start:   2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:  rundeck job automation console
# Description:    rundeckd services.
### END INIT INFO

NAME="rundeck"
PIDFILE=/var/run/$NAME.pid
DAEMON=$JAVA_CMD
DAEMON_ARGS="$RDECK_JVM -cp $BOOTSTRAP_CP com.dtolabs.rundeck.RunServer $RDECK_BASE $RDECK_HTTP_PORT"
rundeckd="$DAEMON $DAEMON_ARGS"

OS_TYPE=`cat /etc/*release*|grep "^ID="|sed 's/\"//g'|awk -F= '{print $NF}'`
if [[ $OS_TYPE == 'debian' ]] || [[ $OS_TYPE == 'ubuntu' ]];
  then
    . /lib/lsb/init-functions
    . /etc/default/$NAME
  else
    . /etc/rc.d/init.d/functions
    . /etc/sysconfig/$NAME
fi

if [[ -n $(which java) ]];
  then
    export JAVA_HOME=$(readlink -f $(which java) | sed "s:/bin/java::")
    export PATH=$PATH:$JAVA_HOME/bin
    JAVA_CMD=$JAVA_HOME/bin/java
  else
    echo "Make sure Java is installed and $JAVA_HOME is setted"
    exit 1
fi


start() {
  echo -n $"Starting $NAME: "
  nohup su -s /bin/bash $RDECK_USER -c "$rundeckd" &>>$RDECK_LOG/service.log &

  if [[ $? -eq 0 ]];
    then
      echo $! > $PIDFILE
      touch /var/run/$NAME
  fi

  return $?
}

stop() {
  echo -n $"Stopping $NAME: "
  kill $(cat $PIDFILE)

  if [[ $? -eq 0 ]];
    then
      rm -f /var/run/$NAME
  fi

  return $?
}

status() {
  if [[ -d "/proc/`cat $PIDFILE`" ]] && [[ -n $(cat /proc/`cat $PIDFILE`/status) ]];
    then
      echo "Service running"
      return 0
    else
      echo "Not running"
      return 1
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  force-reload|restart)
    stop
    start
    ;;
  condrestart)
    if [ -f /var/run/$NAME ];
      then
        stop
        start
    fi
    ;;
  status)
    status
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|condrestart|status}"
    exit 1
esac

exit $?
